module.exports = [
  {
    id: "tag_hair_grooming",
    slug: "hair-grooming",
    group: "Beauty",
    groupId: "beauty",
    display: { "en-NG": "Hair & Grooming", default: "Hair & Grooming" },
    synonyms: ["barber", "barbing salon", "braids", "weave", "wig", "salon", "hairdresser", "locs"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_knotless_braids",
        display: { "en-NG": "Knotless braids", default: "Knotless braids" },
      },
      {
        id: "si_cornrows_didi",
        display: { "en-NG": "Cornrows (didi)", default: "Cornrows (didi)" },
      },
      {
        id: "si_ghana_weaving",
        display: { "en-NG": "Ghana weaving", default: "Ghana weaving" },
      },
      {
        id: "si_box_braids",
        display: { "en-NG": "Box braids", default: "Box braids" },
      },
      {
        id: "si_faux_locs",
        display: { "en-NG": "Faux locs", default: "Faux locs" },
      },
      {
        id: "si_passion_twists",
        display: { "en-NG": "Passion twists", default: "Passion twists" },
      },
      {
        id: "si_wig_installation",
        display: { "en-NG": "Wig installation", default: "Wig installation" },
      },
      {
        id: "si_weave_on",
        display: { "en-NG": "Weave-on", default: "Weave-on" },
      },
      {
        id: "si_locs_retwist",
        display: { "en-NG": "Locs retwist", default: "Locs retwist" },
      },
      {
        id: "si_hair_treatment",
        display: { "en-NG": "Hair treatment", default: "Hair treatment" },
      },
      {
        id: "si_retouching",
        display: { "en-NG": "Retouching", default: "Retouching" },
      },
      {
        id: "si_barbing_haircut",
        display: { "en-NG": "Barbing / haircut", default: "Barbing / haircut" },
      },
      {
        id: "si_beard_trim",
        display: { "en-NG": "Beard trim", default: "Beard trim" },
      },
      {
        id: "si_childrens_braids",
        display: { "en-NG": "Children's braids", default: "Children's braids" },
      },
      {
        id: "si_take_down_old_braids",
        display: { "en-NG": "Take-down (old braids)", default: "Take-down (old braids)" },
      },
      {
        id: "si_threading",
        display: { "en-NG": "Threading", default: "Threading" },
      },
    ],
  },
  {
    id: "tag_makeup_beauty",
    slug: "makeup-beauty",
    group: "Beauty",
    groupId: "beauty",
    display: { "en-NG": "Makeup & Beauty", default: "Makeup & Beauty" },
    synonyms: ["makeup artist", "MUA", "gele", "lashes", "nails", "nail tech"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_bridal_makeup",
        display: { "en-NG": "Bridal makeup", default: "Bridal makeup" },
      },
      {
        id: "si_owambe_party_makeup",
        display: { "en-NG": "Owambe / party makeup", default: "Owambe / party makeup" },
      },
      {
        id: "si_gele_tying",
        display: { "en-NG": "Gele tying", default: "Gele tying" },
      },
      {
        id: "si_makeup_class",
        display: { "en-NG": "Makeup class", default: "Makeup class" },
      },
      {
        id: "si_lash_extensions",
        display: { "en-NG": "Lash extensions", default: "Lash extensions" },
      },
      {
        id: "si_eyebrow_shaping",
        display: { "en-NG": "Eyebrow shaping", default: "Eyebrow shaping" },
      },
      {
        id: "si_manicure",
        display: { "en-NG": "Manicure", default: "Manicure" },
      },
      {
        id: "si_pedicure",
        display: { "en-NG": "Pedicure", default: "Pedicure" },
      },
      {
        id: "si_acrylic_nails",
        display: { "en-NG": "Acrylic nails", default: "Acrylic nails" },
      },
      {
        id: "si_gel_polish",
        display: { "en-NG": "Gel polish", default: "Gel polish" },
      },
      {
        id: "si_nail_fix",
        display: { "en-NG": "Nail fix", default: "Nail fix" },
      },
      {
        id: "si_home_service_makeup",
        display: { "en-NG": "Home service makeup", default: "Home service makeup" },
      },
    ],
  },
  {
    id: "tag_skincare_cosmetics",
    slug: "skincare-cosmetics",
    group: "Beauty",
    groupId: "beauty",
    display: { "en-NG": "Skincare & Cosmetics", default: "Skincare & Cosmetics" },
    synonyms: ["organic cream", "body care", "perfume", "oils", "soap making"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_tailoring_fashion",
    slug: "tailoring-fashion",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Tailoring & Fashion Design", default: "Tailoring & Fashion Design" },
    synonyms: ["tailor", "seamstress", "aso ebi", "fashion designer", "native wear", "agbada"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_agbada",
        display: { "en-NG": "Agbada", default: "Agbada" },
      },
      {
        id: "si_kaftan",
        display: { "en-NG": "Kaftan", default: "Kaftan" },
      },
      {
        id: "si_senator",
        display: { "en-NG": "Senator", default: "Senator" },
      },
      {
        id: "si_ankara_gown",
        display: { "en-NG": "Ankara gown", default: "Ankara gown" },
      },
      {
        id: "si_aso_ebi_outfit",
        display: { "en-NG": "Aso-ebi outfit", default: "Aso-ebi outfit" },
      },
      {
        id: "si_skirt_and_blouse",
        display: { "en-NG": "Skirt & blouse", default: "Skirt & blouse" },
      },
      {
        id: "si_mens_suit",
        display: { "en-NG": "Men's suit", default: "Men's suit" },
      },
      {
        id: "si_bridal_dress",
        display: { "en-NG": "Bridal dress", default: "Bridal dress" },
      },
      {
        id: "si_alterations_adjustment",
        display: { "en-NG": "Alterations / adjustment", default: "Alterations / adjustment" },
      },
      {
        id: "si_school_uniform",
        display: { "en-NG": "School uniform", default: "School uniform" },
      },
      {
        id: "si_corporate_wear",
        display: { "en-NG": "Corporate wear", default: "Corporate wear" },
      },
      {
        id: "si_beadwork_and_stoning",
        display: { "en-NG": "Beadwork & stoning", default: "Beadwork & stoning" },
      },
      {
        id: "si_aso_oke_styling",
        display: { "en-NG": "Aso-oke styling", default: "Aso-oke styling" },
      },
    ],
  },
  {
    id: "tag_fabrics_textiles",
    slug: "fabrics-textiles",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Fabrics & Textiles", default: "Fabrics & Textiles" },
    synonyms: ["ankara", "lace", "aso oke", "adire", "material", "textile"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_ankara_per_yard",
        display: { "en-NG": "Ankara (per yard)", default: "Ankara (per yard)" },
      },
      {
        id: "si_lace",
        display: { "en-NG": "Lace", default: "Lace" },
      },
      {
        id: "si_aso_oke",
        display: { "en-NG": "Aso-oke", default: "Aso-oke" },
      },
      {
        id: "si_adire",
        display: { "en-NG": "Adire", default: "Adire" },
      },
      {
        id: "si_george_wrapper",
        display: { "en-NG": "George wrapper", default: "George wrapper" },
      },
      {
        id: "si_senator_material",
        display: { "en-NG": "Senator material", default: "Senator material" },
      },
      {
        id: "si_guinea_brocade",
        display: { "en-NG": "Guinea brocade", default: "Guinea brocade" },
      },
      {
        id: "si_chiffon",
        display: { "en-NG": "Chiffon", default: "Chiffon" },
      },
    ],
  },
  {
    id: "tag_clothing_shoes",
    slug: "clothing-shoes",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Clothes, Shoes & Bags", default: "Clothes, Shoes & Bags" },
    synonyms: ["boutique", "okrika", "thrift", "bend down select", "footwear", "designer"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_jewelry_accessories",
    slug: "jewelry-accessories",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Jewellery & Accessories", default: "Jewellery & Accessories" },
    synonyms: ["beads", "chains", "watches", "accessories"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_shoemaking_leather",
    slug: "shoemaking-leather",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Shoemaking & Leatherwork", default: "Shoemaking & Leatherwork" },
    synonyms: ["cobbler", "shoe repair", "leather bags", "belts"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_cooked_food",
    slug: "cooked-food",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Cooked Food & Catering", default: "Cooked Food & Catering" },
    synonyms: [
      "mama put",
      "buka",
      "restaurant",
      "caterer",
      "small chops",
      "food vendor",
      "canteen",
    ],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_jollof_rice_party_tray",
        display: { "en-NG": "Jollof rice (party tray)", default: "Jollof rice (party tray)" },
      },
      {
        id: "si_fried_rice",
        display: { "en-NG": "Fried rice", default: "Fried rice" },
      },
      {
        id: "si_ofada_rice_ayamase",
        display: { "en-NG": "Ofada rice & ayamase", default: "Ofada rice & ayamase" },
      },
      {
        id: "si_egusi_soup",
        display: { "en-NG": "Egusi soup", default: "Egusi soup" },
      },
      {
        id: "si_efo_riro",
        display: { "en-NG": "Efo riro", default: "Efo riro" },
      },
      {
        id: "si_amala_ewedu",
        display: { "en-NG": "Amala & ewedu", default: "Amala & ewedu" },
      },
      {
        id: "si_pounded_yam",
        display: { "en-NG": "Pounded yam", default: "Pounded yam" },
      },
      {
        id: "si_suya",
        display: { "en-NG": "Suya", default: "Suya" },
      },
      {
        id: "si_asun",
        display: { "en-NG": "Asun", default: "Asun" },
      },
      {
        id: "si_moi_moi",
        display: { "en-NG": "Moi moi", default: "Moi moi" },
      },
      {
        id: "si_pepper_soup",
        display: { "en-NG": "Pepper soup", default: "Pepper soup" },
      },
      {
        id: "si_small_chops_platter",
        display: { "en-NG": "Small chops platter", default: "Small chops platter" },
      },
      {
        id: "si_cooler_of_rice",
        display: { "en-NG": "Cooler of rice", default: "Cooler of rice" },
      },
      {
        id: "si_per_plate_catering",
        display: { "en-NG": "Per-plate catering", default: "Per-plate catering" },
      },
      {
        id: "si_office_lunch",
        display: { "en-NG": "Office lunch", default: "Office lunch" },
      },
      {
        id: "si_yam_porridge",
        display: { "en-NG": "Yam porridge", default: "Yam porridge" },
      },
    ],
  },
  {
    id: "tag_baking_confectionery",
    slug: "baking-confectionery",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Baking & Confectionery", default: "Baking & Confectionery" },
    synonyms: ["cake", "bread", "puff puff", "pastries", "chin chin", "baker"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_birthday_cake",
        display: { "en-NG": "Birthday cake", default: "Birthday cake" },
      },
      {
        id: "si_wedding_cake",
        display: { "en-NG": "Wedding cake", default: "Wedding cake" },
      },
      {
        id: "si_cupcakes",
        display: { "en-NG": "Cupcakes", default: "Cupcakes" },
      },
      {
        id: "si_chin_chin",
        display: { "en-NG": "Chin chin", default: "Chin chin" },
      },
      {
        id: "si_puff_puff",
        display: { "en-NG": "Puff puff", default: "Puff puff" },
      },
      {
        id: "si_meat_pie",
        display: { "en-NG": "Meat pie", default: "Meat pie" },
      },
      {
        id: "si_samosa",
        display: { "en-NG": "Samosa", default: "Samosa" },
      },
      {
        id: "si_spring_rolls",
        display: { "en-NG": "Spring rolls", default: "Spring rolls" },
      },
      {
        id: "si_doughnuts",
        display: { "en-NG": "Doughnuts", default: "Doughnuts" },
      },
      {
        id: "si_bread",
        display: { "en-NG": "Bread", default: "Bread" },
      },
      {
        id: "si_small_chops_tray",
        display: { "en-NG": "Small chops tray", default: "Small chops tray" },
      },
    ],
  },
  {
    id: "tag_drinks_refreshments",
    slug: "drinks-refreshments",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Drinks & Refreshments", default: "Drinks & Refreshments" },
    synonyms: ["mai shayi", "tea seller", "juice", "zobo", "parfait", "smoothies", "bar"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_zobo",
        display: { "en-NG": "Zobo", default: "Zobo" },
      },
      {
        id: "si_chapman",
        display: { "en-NG": "Chapman", default: "Chapman" },
      },
      {
        id: "si_palm_wine",
        display: { "en-NG": "Palm wine", default: "Palm wine" },
      },
      {
        id: "si_smoothies",
        display: { "en-NG": "Smoothies", default: "Smoothies" },
      },
      {
        id: "si_cocktail_service",
        display: { "en-NG": "Cocktail service", default: "Cocktail service" },
      },
      {
        id: "si_crate_of_soft_drinks",
        display: { "en-NG": "Crate of soft drinks", default: "Crate of soft drinks" },
      },
      {
        id: "si_bottled_water_pack",
        display: { "en-NG": "Bottled water (pack)", default: "Bottled water (pack)" },
      },
    ],
  },
  {
    id: "tag_fresh_produce",
    slug: "fresh-produce",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Fresh Produce", default: "Fresh Produce" },
    synonyms: ["vegetables", "fruits", "pepper", "tomatoes", "foodstuff", "market woman"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_meat_fish",
    slug: "meat-fish",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Meat, Fish & Frozen Foods", default: "Meat, Fish & Frozen Foods" },
    synonyms: ["butcher", "abattoir", "frozen chicken", "fish seller", "cold room"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_provisions_groceries",
    slug: "provisions-groceries",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Provisions & Groceries", default: "Provisions & Groceries" },
    synonyms: ["provision store", "kiosk", "shop", "supermarket", "groceries"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_gas_refill",
    slug: "gas-refill",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Cooking Gas & Refills", default: "Cooking Gas & Refills" },
    synonyms: ["gas plant", "LPG", "gas refill", "cylinder"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_water_supply",
    slug: "water-supply",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Water Supply", default: "Water Supply" },
    synonyms: ["pure water", "bottled water", "dispenser", "tanker", "borehole"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_phone_repair_accessories",
    slug: "phone-repair-accessories",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "Phones & Accessories", default: "Phones & Accessories" },
    synonyms: ["phone repair", "computer village", "chargers", "screen", "phone engineer"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_screen_replacement",
        display: { "en-NG": "Screen replacement", default: "Screen replacement" },
      },
      {
        id: "si_battery_replacement",
        display: { "en-NG": "Battery replacement", default: "Battery replacement" },
      },
      {
        id: "si_charging_port_repair",
        display: { "en-NG": "Charging port repair", default: "Charging port repair" },
      },
      {
        id: "si_software_flashing",
        display: { "en-NG": "Software / flashing", default: "Software / flashing" },
      },
      {
        id: "si_phone_unlocking",
        display: { "en-NG": "Phone unlocking", default: "Phone unlocking" },
      },
      {
        id: "si_screen_protector",
        display: { "en-NG": "Screen protector", default: "Screen protector" },
      },
      {
        id: "si_phone_case",
        display: { "en-NG": "Phone case", default: "Phone case" },
      },
      {
        id: "si_charger",
        display: { "en-NG": "Charger", default: "Charger" },
      },
      {
        id: "si_earphones",
        display: { "en-NG": "Earphones", default: "Earphones" },
      },
      {
        id: "si_uk_used_phone",
        display: { "en-NG": "UK-used phone", default: "UK-used phone" },
      },
      {
        id: "si_swap_trade_in",
        display: { "en-NG": "Swap / trade-in", default: "Swap / trade-in" },
      },
    ],
  },
  {
    id: "tag_electronics_gadgets",
    slug: "electronics-gadgets",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "Electronics & Gadgets", default: "Electronics & Gadgets" },
    synonyms: ["TV", "speakers", "gadgets", "electronics", "alaba"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_computers_it",
    slug: "computers-it",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "Computers & IT Services", default: "Computers & IT Services" },
    synonyms: ["laptop repair", "software", "networking", "CCTV", "IT support"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_generator_repair",
    slug: "generator-repair",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "Generator Sales & Repair", default: "Generator Sales & Repair" },
    synonyms: ["gen repair", "generator engineer", "inverter", "solar"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_generator_servicing",
        display: { "en-NG": "Generator servicing", default: "Generator servicing" },
      },
      {
        id: "si_carburettor_repair",
        display: { "en-NG": "Carburettor repair", default: "Carburettor repair" },
      },
      {
        id: "si_rewinding",
        display: { "en-NG": "Rewinding", default: "Rewinding" },
      },
      {
        id: "si_fuel_pump_repair",
        display: { "en-NG": "Fuel pump repair", default: "Fuel pump repair" },
      },
      {
        id: "si_generator_installation",
        display: { "en-NG": "Generator installation", default: "Generator installation" },
      },
      {
        id: "si_generator_sale",
        display: { "en-NG": "Generator sale", default: "Generator sale" },
      },
      {
        id: "si_emergency_repair",
        display: { "en-NG": "Emergency repair", default: "Emergency repair" },
      },
    ],
  },
  {
    id: "tag_cooling_repair",
    slug: "cooling-repair",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "AC & Fridge Repair", default: "AC & Fridge Repair" },
    synonyms: ["air conditioner", "fridge", "freezer", "cooling technician"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_ac_installation",
        display: { "en-NG": "AC installation", default: "AC installation" },
      },
      {
        id: "si_ac_servicing",
        display: { "en-NG": "AC servicing", default: "AC servicing" },
      },
      {
        id: "si_ac_gas_refill",
        display: { "en-NG": "AC gas refill", default: "AC gas refill" },
      },
      {
        id: "si_fridge_repair",
        display: { "en-NG": "Fridge repair", default: "Fridge repair" },
      },
      {
        id: "si_freezer_repair",
        display: { "en-NG": "Freezer repair", default: "Freezer repair" },
      },
      {
        id: "si_compressor_replacement",
        display: { "en-NG": "Compressor replacement", default: "Compressor replacement" },
      },
      {
        id: "si_deep_freezer_servicing",
        display: { "en-NG": "Deep freezer servicing", default: "Deep freezer servicing" },
      },
    ],
  },
  {
    id: "tag_auto_mechanic",
    slug: "auto-mechanic",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Auto Mechanic", default: "Auto Mechanic" },
    synonyms: ["mechanic", "rewire", "auto electrician", "car service"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_general_servicing",
        display: { "en-NG": "General servicing", default: "General servicing" },
      },
      {
        id: "si_oil_change",
        display: { "en-NG": "Oil change", default: "Oil change" },
      },
      {
        id: "si_brake_pad_replacement",
        display: { "en-NG": "Brake pad replacement", default: "Brake pad replacement" },
      },
      {
        id: "si_computer_diagnosis_scan",
        display: { "en-NG": "Computer diagnosis / scan", default: "Computer diagnosis / scan" },
      },
      {
        id: "si_suspension_repair",
        display: { "en-NG": "Suspension repair", default: "Suspension repair" },
      },
      {
        id: "si_car_ac_repair",
        display: { "en-NG": "Car AC repair", default: "Car AC repair" },
      },
      {
        id: "si_clutch_repair",
        display: { "en-NG": "Clutch repair", default: "Clutch repair" },
      },
      {
        id: "si_roadside_call_out",
        display: { "en-NG": "Roadside call-out", default: "Roadside call-out" },
      },
    ],
  },
  {
    id: "tag_auto_parts",
    slug: "auto-parts",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Auto Spare Parts", default: "Auto Spare Parts" },
    synonyms: ["ladipo", "spare parts", "motor parts"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_panel_beating",
    slug: "panel-beating",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Panel Beating & Painting", default: "Panel Beating & Painting" },
    synonyms: ["panel beater", "car painting", "body work"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_vulcanizing_tyres",
    slug: "vulcanizing-tyres",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Tyres & Vulcanizing", default: "Tyres & Vulcanizing" },
    synonyms: ["vulcanizer", "tyre", "wheel balancing"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_transport_rides",
    slug: "transport-rides",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Transport & Rides", default: "Transport & Rides" },
    synonyms: ["okada", "keke", "bus", "taxi", "driver", "car hire"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_delivery",
    slug: "delivery",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Delivery & Dispatch", default: "Delivery & Dispatch" },
    synonyms: ["dispatch rider", "courier", "logistics", "errand", "waybill"],
    regulated: {
      requires: ["serviceZones"],
      unlocks: ["courier_surfaces"],
    },
    markets: ["NG"],
  },
  {
    id: "tag_carpentry_furniture",
    slug: "carpentry-furniture",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Carpentry & Furniture", default: "Carpentry & Furniture" },
    synonyms: ["carpenter", "furniture maker", "upholstery", "cushion"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_welding_metalwork",
    slug: "welding-metalwork",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Welding & Metalwork", default: "Welding & Metalwork" },
    synonyms: ["welder", "iron gate", "burglary proof", "aluminium"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_electrician",
    slug: "electrician",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Electrician", default: "Electrician" },
    synonyms: ["house wiring", "electrical", "light"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_house_wiring",
        display: { "en-NG": "House wiring", default: "House wiring" },
      },
      {
        id: "si_socket_and_switch_repair",
        display: { "en-NG": "Socket & switch repair", default: "Socket & switch repair" },
      },
      {
        id: "si_changeover_switch",
        display: { "en-NG": "Changeover switch", default: "Changeover switch" },
      },
      {
        id: "si_distribution_board",
        display: { "en-NG": "Distribution board", default: "Distribution board" },
      },
      {
        id: "si_fault_finding",
        display: { "en-NG": "Fault finding", default: "Fault finding" },
      },
      {
        id: "si_light_fitting",
        display: { "en-NG": "Light fitting", default: "Light fitting" },
      },
      {
        id: "si_solar_inverter_installation",
        display: {
          "en-NG": "Solar / inverter installation",
          default: "Solar / inverter installation",
        },
      },
      {
        id: "si_meter_connection",
        display: { "en-NG": "Meter connection", default: "Meter connection" },
      },
      {
        id: "si_rewiring",
        display: { "en-NG": "Rewiring", default: "Rewiring" },
      },
    ],
  },
  {
    id: "tag_plumbing",
    slug: "plumbing",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Plumbing", default: "Plumbing" },
    synonyms: ["plumber", "pipe", "water system"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_leaking_tap_repair",
        display: { "en-NG": "Leaking tap repair", default: "Leaking tap repair" },
      },
      {
        id: "si_burst_pipe_repair",
        display: { "en-NG": "Burst pipe repair", default: "Burst pipe repair" },
      },
      {
        id: "si_blocked_drain",
        display: { "en-NG": "Blocked drain", default: "Blocked drain" },
      },
      {
        id: "si_toilet_wc_installation",
        display: { "en-NG": "Toilet / WC installation", default: "Toilet / WC installation" },
      },
      {
        id: "si_sink_installation",
        display: { "en-NG": "Sink installation", default: "Sink installation" },
      },
      {
        id: "si_water_heater_repair",
        display: { "en-NG": "Water heater repair", default: "Water heater repair" },
      },
      {
        id: "si_water_pump_installation",
        display: { "en-NG": "Water pump installation", default: "Water pump installation" },
      },
      {
        id: "si_full_house_plumbing",
        display: { "en-NG": "Full house plumbing", default: "Full house plumbing" },
      },
      {
        id: "si_emergency_call_out",
        display: { "en-NG": "Emergency call-out", default: "Emergency call-out" },
      },
    ],
  },
  {
    id: "tag_painting_pop",
    slug: "painting-pop",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Painting & POP", default: "Painting & POP" },
    synonyms: ["painter", "screeding", "POP ceiling", "interior"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_interior_painting",
        display: { "en-NG": "Interior painting", default: "Interior painting" },
      },
      {
        id: "si_exterior_painting",
        display: { "en-NG": "Exterior painting", default: "Exterior painting" },
      },
      {
        id: "si_pop_ceiling",
        display: { "en-NG": "POP ceiling", default: "POP ceiling" },
      },
      {
        id: "si_screeding",
        display: { "en-NG": "Screeding", default: "Screeding" },
      },
      {
        id: "si_wall_design_stencil",
        display: { "en-NG": "Wall design / stencil", default: "Wall design / stencil" },
      },
      {
        id: "si_wallpaper",
        display: { "en-NG": "Wallpaper", default: "Wallpaper" },
      },
      {
        id: "si_pop_repair",
        display: { "en-NG": "POP repair", default: "POP repair" },
      },
      {
        id: "si_touch_up",
        display: { "en-NG": "Touch-up", default: "Touch-up" },
      },
    ],
  },
  {
    id: "tag_building_construction",
    slug: "building-construction",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Building & Construction", default: "Building & Construction" },
    synonyms: ["bricklayer", "mason", "tiler", "builder", "site work"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_laundry_drycleaning",
    slug: "laundry-drycleaning",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Laundry & Dry Cleaning", default: "Laundry & Dry Cleaning" },
    synonyms: ["washman", "laundry", "ironing", "dry cleaner"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_cleaning_fumigation",
    slug: "cleaning-fumigation",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Cleaning & Fumigation", default: "Cleaning & Fumigation" },
    synonyms: ["cleaner", "house cleaning", "fumigation", "pest control"],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_deep_cleaning",
        display: { "en-NG": "Deep cleaning", default: "Deep cleaning" },
      },
      {
        id: "si_post_construction_cleaning",
        display: { "en-NG": "Post-construction cleaning", default: "Post-construction cleaning" },
      },
      {
        id: "si_move_in_cleaning",
        display: { "en-NG": "Move-in cleaning", default: "Move-in cleaning" },
      },
      {
        id: "si_office_cleaning",
        display: { "en-NG": "Office cleaning", default: "Office cleaning" },
      },
      {
        id: "si_fumigation_pest_control",
        display: { "en-NG": "Fumigation / pest control", default: "Fumigation / pest control" },
      },
      {
        id: "si_sofa_and_rug_washing",
        display: { "en-NG": "Sofa & rug washing", default: "Sofa & rug washing" },
      },
      {
        id: "si_water_tank_cleaning",
        display: { "en-NG": "Water tank cleaning", default: "Water tank cleaning" },
      },
    ],
  },
  {
    id: "tag_tutoring_lessons",
    slug: "tutoring-lessons",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Tutoring & Lessons", default: "Tutoring & Lessons" },
    synonyms: ["lesson teacher", "home lesson", "tutor", "JAMB", "WAEC", "music lessons"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_housing_agent",
    slug: "housing-agent",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Housing Agent", default: "Housing Agent" },
    synonyms: ["house agent", "real estate", "rent", "shortlet", "property"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_pos_agent_banking",
    slug: "pos-agent-banking",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "POS & Agent Banking", default: "POS & Agent Banking" },
    synonyms: [
      "POS",
      "agent banking",
      "transfer",
      "withdrawal",
      "recharge card",
      "airtime",
      "data",
    ],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_printing_branding",
    slug: "printing-branding",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Printing & Branding", default: "Printing & Branding" },
    synonyms: ["business cards", "banner", "flex", "souvenirs", "press"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_graphics_digital",
    slug: "graphics-digital",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Graphics & Digital Services", default: "Graphics & Digital Services" },
    synonyms: ["graphic design", "flyer", "social media", "website"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_photography_video",
    slug: "photography-video",
    group: "Events",
    groupId: "events",
    display: { "en-NG": "Photography & Video", default: "Photography & Video" },
    synonyms: ["photographer", "videographer", "photo studio", "passport"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_events_planning",
    slug: "events-planning",
    group: "Events",
    groupId: "events",
    display: { "en-NG": "Events & Party Planning", default: "Events & Party Planning" },
    synonyms: [
      "event planner",
      "decorator",
      "MC",
      "canopy",
      "chairs",
      "rentals",
      "asoebi coordination",
    ],
    regulated: null,
    markets: ["NG"],
    suggestedItems: [
      {
        id: "si_full_event_planning",
        display: { "en-NG": "Full event planning", default: "Full event planning" },
      },
      {
        id: "si_decoration",
        display: { "en-NG": "Decoration", default: "Decoration" },
      },
      {
        id: "si_chair_and_canopy_rental",
        display: { "en-NG": "Chair & canopy rental", default: "Chair & canopy rental" },
      },
      {
        id: "si_ushering_service",
        display: { "en-NG": "Ushering service", default: "Ushering service" },
      },
      {
        id: "si_mc_compere",
        display: { "en-NG": "MC / compere", default: "MC / compere" },
      },
      {
        id: "si_souvenir_sourcing",
        display: { "en-NG": "Souvenir sourcing", default: "Souvenir sourcing" },
      },
      {
        id: "si_traditional_wedding_setup",
        display: { "en-NG": "Traditional wedding setup", default: "Traditional wedding setup" },
      },
      {
        id: "si_serving_staff",
        display: { "en-NG": "Serving staff", default: "Serving staff" },
      },
    ],
  },
  {
    id: "tag_music_dj",
    slug: "music-dj",
    group: "Events",
    groupId: "events",
    display: { "en-NG": "Music & DJ", default: "Music & DJ" },
    synonyms: ["DJ", "live band", "sound system", "hypeman"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_farming_agro",
    slug: "farming-agro",
    group: "Agro",
    groupId: "agro",
    display: { "en-NG": "Farming & Agro", default: "Farming & Agro" },
    synonyms: ["poultry", "catfish", "fish farm", "piggery", "farm produce", "agro"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_recycling_scrap",
    slug: "recycling-scrap",
    group: "Agro",
    groupId: "agro",
    display: { "en-NG": "Recycling & Scrap", default: "Recycling & Scrap" },
    synonyms: ["condemn", "scrap", "aluminium buyer", "recycling"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_arts_crafts",
    slug: "arts-crafts",
    group: "Crafts",
    groupId: "crafts",
    display: { "en-NG": "Arts & Crafts", default: "Arts & Crafts" },
    synonyms: ["artist", "beadwork", "tie dye", "handmade", "crafts"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_other",
    slug: "other",
    group: "Other",
    groupId: "other",
    display: { "en-NG": "Other", default: "Other" },
    synonyms: ["miscellaneous", "various", "other"],
    regulated: null,
    markets: ["NG"],
  },
];
