module.exports = [
  {
    id: "tag_hair_grooming",
    slug: "hair-grooming",
    group: "Beauty",
    groupId: "beauty",
    display: { "en-NG": "Hair & Grooming", default: "Hair & Grooming" },
    synonyms: ["barber", "barbing salon", "braids", "weave", "wig", "salon", "hairdresser", "locs"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_makeup_beauty",
    slug: "makeup-beauty",
    group: "Beauty",
    groupId: "beauty",
    display: { "en-NG": "Makeup & Beauty", default: "Makeup & Beauty" },
    synonyms: ["makeup artist", "MUA", "gele", "lashes", "nails", "nail tech"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_skincare_cosmetics",
    slug: "skincare-cosmetics",
    group: "Beauty",
    groupId: "beauty",
    display: { "en-NG": "Skincare & Cosmetics", default: "Skincare & Cosmetics" },
    synonyms: ["organic cream", "body care", "perfume", "oils", "soap making"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_tailoring_fashion",
    slug: "tailoring-fashion",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Tailoring & Fashion Design", default: "Tailoring & Fashion Design" },
    synonyms: ["tailor", "seamstress", "aso ebi", "fashion designer", "native wear", "agbada"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_fabrics_textiles",
    slug: "fabrics-textiles",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Fabrics & Textiles", default: "Fabrics & Textiles" },
    synonyms: ["ankara", "lace", "aso oke", "adire", "material", "textile"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_clothing_shoes",
    slug: "clothing-shoes",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Clothes, Shoes & Bags", default: "Clothes, Shoes & Bags" },
    synonyms: ["boutique", "okrika", "thrift", "bend down select", "footwear", "designer"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_jewelry_accessories",
    slug: "jewelry-accessories",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Jewellery & Accessories", default: "Jewellery & Accessories" },
    synonyms: ["beads", "chains", "watches", "accessories"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_shoemaking_leather",
    slug: "shoemaking-leather",
    group: "Fashion",
    groupId: "fashion",
    display: { "en-NG": "Shoemaking & Leatherwork", default: "Shoemaking & Leatherwork" },
    synonyms: ["cobbler", "shoe repair", "leather bags", "belts"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_cooked_food",
    slug: "cooked-food",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Cooked Food & Catering", default: "Cooked Food & Catering" },
    synonyms: [
      "mama put",
      "buka",
      "restaurant",
      "caterer",
      "small chops",
      "food vendor",
      "canteen",
    ],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_baking_confectionery",
    slug: "baking-confectionery",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Baking & Confectionery", default: "Baking & Confectionery" },
    synonyms: ["cake", "bread", "puff puff", "pastries", "chin chin", "baker"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_drinks_refreshments",
    slug: "drinks-refreshments",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Drinks & Refreshments", default: "Drinks & Refreshments" },
    synonyms: ["mai shayi", "tea seller", "juice", "zobo", "parfait", "smoothies", "bar"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_fresh_produce",
    slug: "fresh-produce",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Fresh Produce", default: "Fresh Produce" },
    synonyms: ["vegetables", "fruits", "pepper", "tomatoes", "foodstuff", "market woman"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_meat_fish",
    slug: "meat-fish",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Meat, Fish & Frozen Foods", default: "Meat, Fish & Frozen Foods" },
    synonyms: ["butcher", "abattoir", "frozen chicken", "fish seller", "cold room"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_provisions_groceries",
    slug: "provisions-groceries",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Provisions & Groceries", default: "Provisions & Groceries" },
    synonyms: ["provision store", "kiosk", "shop", "supermarket", "groceries"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_gas_refill",
    slug: "gas-refill",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Cooking Gas & Refills", default: "Cooking Gas & Refills" },
    synonyms: ["gas plant", "LPG", "gas refill", "cylinder"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_water_supply",
    slug: "water-supply",
    group: "Food",
    groupId: "food",
    display: { "en-NG": "Water Supply", default: "Water Supply" },
    synonyms: ["pure water", "bottled water", "dispenser", "tanker", "borehole"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_phone_repair_accessories",
    slug: "phone-repair-accessories",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "Phones & Accessories", default: "Phones & Accessories" },
    synonyms: ["phone repair", "computer village", "chargers", "screen", "phone engineer"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_electronics_gadgets",
    slug: "electronics-gadgets",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "Electronics & Gadgets", default: "Electronics & Gadgets" },
    synonyms: ["TV", "speakers", "gadgets", "electronics", "alaba"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_computers_it",
    slug: "computers-it",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "Computers & IT Services", default: "Computers & IT Services" },
    synonyms: ["laptop repair", "software", "networking", "CCTV", "IT support"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_generator_repair",
    slug: "generator-repair",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "Generator Sales & Repair", default: "Generator Sales & Repair" },
    synonyms: ["gen repair", "generator engineer", "inverter", "solar"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_cooling_repair",
    slug: "cooling-repair",
    group: "Tech",
    groupId: "tech",
    display: { "en-NG": "AC & Fridge Repair", default: "AC & Fridge Repair" },
    synonyms: ["air conditioner", "fridge", "freezer", "cooling technician"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_auto_mechanic",
    slug: "auto-mechanic",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Auto Mechanic", default: "Auto Mechanic" },
    synonyms: ["mechanic", "rewire", "auto electrician", "car service"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_auto_parts",
    slug: "auto-parts",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Auto Spare Parts", default: "Auto Spare Parts" },
    synonyms: ["ladipo", "spare parts", "motor parts"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_panel_beating",
    slug: "panel-beating",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Panel Beating & Painting", default: "Panel Beating & Painting" },
    synonyms: ["panel beater", "car painting", "body work"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_vulcanizing_tyres",
    slug: "vulcanizing-tyres",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Tyres & Vulcanizing", default: "Tyres & Vulcanizing" },
    synonyms: ["vulcanizer", "tyre", "wheel balancing"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_transport_rides",
    slug: "transport-rides",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Transport & Rides", default: "Transport & Rides" },
    synonyms: ["okada", "keke", "bus", "taxi", "driver", "car hire"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_delivery",
    slug: "delivery",
    group: "Auto",
    groupId: "auto",
    display: { "en-NG": "Delivery & Dispatch", default: "Delivery & Dispatch" },
    synonyms: ["dispatch rider", "courier", "logistics", "errand", "waybill"],
    regulated: {
      requires: ["serviceZones"],
      unlocks: ["courier_surfaces"],
    },
    markets: ["NG"],
  },
  {
    id: "tag_carpentry_furniture",
    slug: "carpentry-furniture",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Carpentry & Furniture", default: "Carpentry & Furniture" },
    synonyms: ["carpenter", "furniture maker", "upholstery", "cushion"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_welding_metalwork",
    slug: "welding-metalwork",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Welding & Metalwork", default: "Welding & Metalwork" },
    synonyms: ["welder", "iron gate", "burglary proof", "aluminium"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_electrician",
    slug: "electrician",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Electrician", default: "Electrician" },
    synonyms: ["house wiring", "electrical", "light"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_plumbing",
    slug: "plumbing",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Plumbing", default: "Plumbing" },
    synonyms: ["plumber", "pipe", "water system"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_painting_pop",
    slug: "painting-pop",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Painting & POP", default: "Painting & POP" },
    synonyms: ["painter", "screeding", "POP ceiling", "interior"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_building_construction",
    slug: "building-construction",
    group: "Building",
    groupId: "building",
    display: { "en-NG": "Building & Construction", default: "Building & Construction" },
    synonyms: ["bricklayer", "mason", "tiler", "builder", "site work"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_laundry_drycleaning",
    slug: "laundry-drycleaning",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Laundry & Dry Cleaning", default: "Laundry & Dry Cleaning" },
    synonyms: ["washman", "laundry", "ironing", "dry cleaner"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_cleaning_fumigation",
    slug: "cleaning-fumigation",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Cleaning & Fumigation", default: "Cleaning & Fumigation" },
    synonyms: ["cleaner", "house cleaning", "fumigation", "pest control"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_tutoring_lessons",
    slug: "tutoring-lessons",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Tutoring & Lessons", default: "Tutoring & Lessons" },
    synonyms: ["lesson teacher", "home lesson", "tutor", "JAMB", "WAEC", "music lessons"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_housing_agent",
    slug: "housing-agent",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Housing Agent", default: "Housing Agent" },
    synonyms: ["house agent", "real estate", "rent", "shortlet", "property"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_pos_agent_banking",
    slug: "pos-agent-banking",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "POS & Agent Banking", default: "POS & Agent Banking" },
    synonyms: [
      "POS",
      "agent banking",
      "transfer",
      "withdrawal",
      "recharge card",
      "airtime",
      "data",
    ],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_printing_branding",
    slug: "printing-branding",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Printing & Branding", default: "Printing & Branding" },
    synonyms: ["business cards", "banner", "flex", "souvenirs", "press"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_graphics_digital",
    slug: "graphics-digital",
    group: "Services",
    groupId: "services",
    display: { "en-NG": "Graphics & Digital Services", default: "Graphics & Digital Services" },
    synonyms: ["graphic design", "flyer", "social media", "website"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_photography_video",
    slug: "photography-video",
    group: "Events",
    groupId: "events",
    display: { "en-NG": "Photography & Video", default: "Photography & Video" },
    synonyms: ["photographer", "videographer", "photo studio", "passport"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_events_planning",
    slug: "events-planning",
    group: "Events",
    groupId: "events",
    display: { "en-NG": "Events & Party Planning", default: "Events & Party Planning" },
    synonyms: [
      "event planner",
      "decorator",
      "MC",
      "canopy",
      "chairs",
      "rentals",
      "asoebi coordination",
    ],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_music_dj",
    slug: "music-dj",
    group: "Events",
    groupId: "events",
    display: { "en-NG": "Music & DJ", default: "Music & DJ" },
    synonyms: ["DJ", "live band", "sound system", "hypeman"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_farming_agro",
    slug: "farming-agro",
    group: "Agro",
    groupId: "agro",
    display: { "en-NG": "Farming & Agro", default: "Farming & Agro" },
    synonyms: ["poultry", "catfish", "fish farm", "piggery", "farm produce", "agro"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_recycling_scrap",
    slug: "recycling-scrap",
    group: "Agro",
    groupId: "agro",
    display: { "en-NG": "Recycling & Scrap", default: "Recycling & Scrap" },
    synonyms: ["condemn", "scrap", "aluminium buyer", "recycling"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_arts_crafts",
    slug: "arts-crafts",
    group: "Crafts",
    groupId: "crafts",
    display: { "en-NG": "Arts & Crafts", default: "Arts & Crafts" },
    synonyms: ["artist", "beadwork", "tie dye", "handmade", "crafts"],
    regulated: null,
    markets: ["NG"],
  },
  {
    id: "tag_other",
    slug: "other",
    group: "Other",
    groupId: "other",
    display: { "en-NG": "Other", default: "Other" },
    synonyms: ["miscellaneous", "various", "other"],
    regulated: null,
    markets: ["NG"],
  },
];
