module.exports = Object.freeze({
  addUserPriceToProduct: require("./addUserPriceToProduct"),

  callBatchSMSService: require("./callBatchSMSService"),
  callChatGPTApi: require("./callChatGPTApi"),
  callPushService: require("./callPushService"),

  chatIdByUser: require("./chatIdByUser"),

  checkHash: require("./checkHash"),
  checkHashDidWW: require("./checkHashDidWW"),
  checkIfCarrierIsAllowed: require("./checkIfCarrierIsAllowed"),
  checkProductCategoryGroup: require("./checkProductCategoryGroup"),
  checkQriosBalance: require("./checkQriosBalance"),
  checkReCaptcha: require("./checkReCaptcha"),
  checkVideoForWatermarks: require("./checkVideoForWatermarks"),

  clearCookies: require("./clearCookies"),
  compareAudioWithSoundalike: require("./compareAudioWithSoundalike"),
  compressVideo: require("./compressVideo"),
  convertToDash: require("./convertToDash"),
  convertToHSL: require("./convertToHSL"),
  convertToMP3: require("./convertToMP3"),
  countryFromBinNumber: require("./countryFromBinNumber"),
  countryFromIP: require("./countryFromIP"),

  deleteHslFile: require("./deleteHslFile"),

  eligibleForUSSD: require("./eligibleForUSSD"),
  encodeLnUrl: require("./encodeLnUrl"),
  escapeRegExp: require("./escapeRegExp"),
  executeCommand: require("./executeCommand"),

  filterExpiredMemberships: require("./filterExpiredMemberships"),
  formatPhoneNumber: require("./formatPhoneNumber"),
  formParse: require("./formParse"),

  generateFakeMerchantCode: require("./generateFakeMerchantCode"),
  generateImageThumbnail: require("./generateImageThumbnail"),
  generateRandomNumber: require("./generateRandomNumber"),
  generateSocialMediaWithLinks: require("./generateSocialMediaWithLinks"),
  generateThumbnailFromImage: require("./generateThumbnailFromImage"),

  getAddressFromCoordinates: require("./getAddressFromCoordinates"),
  getAllBankAccountsWithMsisdn: require("./getAllBankAccountsWithMsisdn"),
  getCarrier: require("./getCarrier"),
  getConversionRates: require("./getConversionRates"),
  getCountryBanDuration: require("./getCountryBanDuration"),
  getCountryCodeFromPhoneNumber: require("./getCountryCodeFromPhoneNumber"),
  getCountryFromIpAddress: require("./getCountryFromIpAddress"),
  getCurrencyFromCountryCode: require("./getCurrencyFromCountryCode"),
  getCustomerActivationData: require("./getCustomerActivationData"),
  getDataProductBySku: require("./getDataProductBySku"),
  getGPTAssistantResponse: require("./getGPTAssistantResponse"),
  getHash: require("./getHash"),
  getLocalDateString: require("./getLocalDateString"),
  getMCashErrorCode: require("./getMCashErrorCode"),
  getNigerianCarrier: require("./getNigerianCarrier"),
  getObjectIdFromRoomID: require("./getObjectIdFromRoomID"),
  getPpnLogoImage: require("./getPpnLogoImage"),
  getRandomString: require("./getRandomString"),
  getTelco: require("./getTelco"),
  getUsersConversionRate: require("./getUsersConversionRate"),
  getVideoScreenshots: require("./getVideoScreenshots"),

  handleAudioFile: require("./handleAudioFile"),
  handleImageFile: require("./handleImageFile"),
  hash: require("./hash"),
  hideBadWords: require("./hideBadWords"),

  isEmail: require("./isEmail"),
  isObjectId: require("./isObjectId"),
  isPositiveInteger: require("./isPositiveInteger"),
  isProductForSale: require("./isProductForSale"),
  isUserCommunityMember: require("./isUserCommunityMember"),
  isUserTribeMember: require("./isUserTribeMember"),
  isValidObjectId: require("./isValidObjectId"),

  makeHash: require("./makeHash"),

  replaceAll: require("./replaceAll"),
  resizeImage: require("./resizeImage"),
  rotateVideo: require("./rotateVideo"),
  roundNumber: require("./roundNumber"),

  sendEmailFromTemplate: require("./sendEmailFromTemplate"),
  sendEmailWithSG: require("./sendEmailWithSG"),
  sendFlomPush: require("./sendFlomPush"),
  sendMessageToChat: require("./sendMessageToChat"),
  sendMessageToLiveStream: require("./sendMessageToLiveStream"),
  sendPushNotifications: require("./sendPushNotifications"),
  sendRequest: require("./sendRequest"),
  sendSMS: require("./sendSMS"),
  sendSmsNew: require("./sendSmsNew"),
  sendSMSv2: require("./sendSMSv2"),
  sendWhatsAppMessage: require("./sendWhatsAppMessage"),
  sendWritingNewsLetterFromTemplate: require("./sendWritingNewsLetterFromTemplate"),

  setCookies: require("./setCookies"),
  shorten: require("./shorten"),
  stripPrivateData: require("./stripPrivateData"),
  syncProductsCategories: require("./syncProductsCategories"),
  toObjectId: require("./toObjectId"),

  wait: require("./wait"),

  yearsFromBirthDate: require("./yearsFromBirthDate"),
});
