module.exports = Object.freeze({
  AccessRecord: require("./AccessRecord"),
  AdminPageUser: require("./AdminPageUser"),
  ApiAccessLog: require("./APIAccessLog"),
  AppVersion: require("./AppVersion"),
  Auction: require("./Auction"),

  BalanceEmoji: require("./BalanceEmoji"),
  Bank: require("./Bank"),
  BannedNumber: require("./BannedNumber"),
  BinLookup: require("./BinLookup"),
  BlessPacket: require("./BlessPacket"),
  BlockedChatGPTCountry: require("./BlockedChatGPTCountry"),
  BlockedNumber: require("./BlockedNumber"),
  BlockedThirdPartyProduct: require("./BlockedThirdPartyProduct"),
  Brand: require("./Brand"),

  CallLog: require("./CallLog"),
  Category: require("./Category"),
  Color: require("./Color"),
  Configuration: require("./Configuration"),
  ContactTicket: require("./ContactTicket"),
  ConversionRate: require("./ConversionRate"),
  CountryWideBan: require("./CountryWideBan"),
  CreditConversionRate: require("./CreditConversionRate"),
  CreditPackage: require("./CreditPackage"),
  CreditTransferLimit: require("./CreditTransferLimit"),

  DidWWLog: require("./DidWWLog"),
  DidWWNumber: require("./DidWWNumber"),

  EmojiSet: require("./EmojiSet"),

  Favorite: require("./Favorite"),
  Fee: require("./Fee"),
  Feedback: require("./Feedback"),
  FlomFile: require("./FlomFile"),
  FlomMessage: require("./FlomMessage"),
  Fulfillment: require("./Fulfillment"),

  Gender: require("./Gender"),
  Group: require("./Group"),
  GroupRequestTransfer: require("./GroupRequestTransfer"),
  GroupTransfer: require("./GroupTransfer"),

  History: require("./History"),

  IdApplication: require("./IdApplication"),
  InviteMessage: require("./InviteMessage"),
  IpAddress: require("./IPAddress"),

  LiveStream: require("./LiveStream"),
  LoginAttempt: require("./LoginAttempt"),

  MainCategory: require("./MainCategory"),
  MarketingMessage: require("./MarketingMessage"),
  MarketingNotification: require("./MarketingNotification"),
  MarketingNotificationTemplate: require("./MarketingNotificationTemplate"),
  Membership: require("./Membership"),
  MerchantApplication: require("./MerchantApplication"),

  NonFlomContact: require("./NonFlomContact"),
  Note: require("./Note"),
  Notification: require("./Notification"),
  NumberDefaultCarrier: require("./NumberDefaultCarrier"),

  OfflineMessage: require("./OfflineMessage"),
  Order: require("./Order"),
  Organization: require("./Organization"),
  OrganizationSettings: require("./OrganizationSettings"),

  PaymentLog: require("./PaymentLog"),
  PaymentMethod: require("./PaymentMethod"),
  Payout: require("./Payout"),
  PayoutLimit: require("./PayoutLimit"),
  Product: require("./Product"),
  ProductModerationLog: require("./ProductModerationLog"),

  RecurringPayment: require("./RecurringPayment"),
  RegistrationLink: require("./RegistrationLink"),
  RequestTransfer: require("./RequestTransfer"),
  Review: require("./Review"),
  Room: require("./Room"),

  SatsReservation: require("./SatsReservation"),
  Size: require("./Size"),
  SmsData: require("./SMSData"),
  SmsPrice: require("./SMSPrice"),
  Sound: require("./Sound"),
  SprayValue: require("./SprayValue"),
  Sticker: require("./Sticker"),
  SubCategory: require("./SubCategory"),
  SubType: require("./SubType"),
  SupportTicket: require("./SupportTicket"),

  FlomTag: require("./FlomTag"),
  TaxRate: require("./TaxRate"),
  TemporaryBan: require("./TemporaryBan"),
  Test: require("./Test"),
  ThirdPartyProduct: require("./ThirdPartyProduct"),
  Transaction: require("./Transaction"),
  Transfer: require("./Transfer"),
  TransferType: require("./TransferType"),
  Tribe: require("./Tribe"),
  Type: require("./Type"),

  User: require("./User"),
  UserCategoryInteraction: require("./UserCategoryInteraction"),
  UserTagInteraction: require("./UserTagInteraction"),
  UserContact: require("./UserContact"),

  VehicleMake: require("./VehicleMake"),
  VehicleModel: require("./VehicleModel"),
  View: require("./View"),
  ViewForYou: require("./ViewForYou"),

  Webhook: require("./Webhook"),
  WhatsAppPrice: require("./WhatsAppPrice"),
  WhatsAppUserMapping: require("./WhatsAppUserMapping"),

  TalkTicket: require("./TalkTicket"),
});
